### ISSUE TITLE
Transform list of speed limits to OSM syntax

### ISSUE THREAD

**Issue by westnordost** [stadiamaps/osm-default-speeds#3]
Step 2 of the conversion would be to convert speed values like `70 (3.5t)` to [conditional speed restrictions](https://wiki.openstreetmap.org/wiki/Conditional_restrictions) and speed restrictions for different vehicle types also to OSM syntax.
Of course any other format would be possible too, but any router that works with OSM data will need to have a parser for OSM syntax anyway.

This conversion can be done already before relating the speed limits table to the 2nd table in that wiki page.

**Comment by westnordost** [comment]
Example. This  
```json
"(default)": [
  "70",
  "50 (trailer)",
  "45 (0.8t trailer)",
  "55 (7.5t)",
  "40 (7.5t, trailer)",
  "50 (12t, trailer)",
  "40 (12t, articulated)"],
"goods": [
  "50",
  "55 (7.5t)",
  "40 (7.5t, trailer)",
  "50 (12t, trailer)",
  "40 (12t, articulated)"],
"motorcycle": ["50"]
```
becomes probably* this
```json
"maxspeed": "70",
"maxspeed:conditional": "50 @ (trailer); 45 @ (trailerweight>0.8); 55 @ (weightrating>7.5); 40 @ (weightrating>7.5 AND trailer); 50 @ (weightrating>12 AND trailer); 40 @ (weightrating>12 AND articulated)"
"maxspeed:goods": "50",
"maxspeed:goods:conditional": "55 @ (weightrating>7.5); 40 @ (weightrating>7.5 AND trailer); 50 @ (weightrating>12 AND trailer); 40 @ (weightrating>12 AND articulated)"
"maxspeed:motorcycle": "50"
```

\* see next comment

**Edit:** Of course a further intermediate step would be possible as well, for example just convert the conditionals to OSM syntax but keep it as a list.

**Comment by westnordost** [comment]
The conversion table would be:
* `$t` → `weightrating>$`*
* `empty $t` → `emptyweight>$`*
* `capacity $t` → `weightcapacity>$`*
* `$m` → `length>$`
* `$ axles` → `axles>=$`*
* `$ seats` → `seats>=$`*
* `articulated` → `articulated`**
* `trailer` → `trailer`**
* `$t trailer` → `trailerweight>$`*
* `caravan` → `caravan`**
* opening hours syntax stays the same

\* probably, not defined in wiki
\** probably, not defined in wiki. Or, convert to vehicle classes `hgv_articulated`, `hgv_trailer`, `bus_trailer` etc etc

If anything else turns up in the table, the script should emit an error/warning that this property is unknown and a mapping cannot be made.

**Comment by ianthetechie** [comment]
Just a quick note than I haven't forgotten about this. I've finally got some time this weekend and am working on it.

I realized pretty quickly that the current approach with regexes is not going to be powerful enough to handle the variety of expressions, conditions, etc. and is not very useful as a validator. As such, I've replaced the regex with a proper EBNF grammar, parser, etc. so it will be much easier to extend the grammar and change output formats.

**Comment by westnordost** [comment]
Wow. I am curious how this will look in the code

**Comment by ianthetechie** [comment]
I'm having some hesitation about collapsing the hierarchy because not all of them are valid OSM objects (i.e. plain english "service road" is not, but `maxspeed:motorcycle` is valid). What are your thoughts about leaving it as on the PR I just opened and allowing interested clients to drill down into the particular special cases they are aware of?

As always, thanks for your input and hard work in laying the groundwork!

**Comment by westnordost** [comment]
I do not understand the question. Can you give an example?

**Comment by ianthetechie** [comment]
Sure. Basically, instead of what you proposed above, I have done the following. I think that "flattening" the structure doesn't perfectly map to OSM tags, and (at least in my opinion) would be more difficult for applications to use. But I will defer to you on this point since this format is primarily for your benefit, and we will be creating other output formats for various uses (like Valhalla) later.

```json
{
  "(default)": {
    "maxspeed": "70",
    "maxspeed:conditional": "50 @ (trailer); 45 @ (trailerweight>0.8); 55 @ (weightrating>7.5); 40 @ (weightrating>7.5 AND trailer); 50 @ (weightrating>12 AND trailer); 40 @ (weightrating>12 AND articulated)"
  },
  "goods": {
    "maxspeed": "50",
    "maxspeed:conditional": "55 @ (weightrating>7.5); 40 @ (weightrating>7.5 AND trailer); 50 @ (weightrating>12 AND trailer); 40 @ (weightrating>12 AND articulated)"
  },
  "motorcycle": {
    "maxspeed": "50"
  }
}
```

**Comment by westnordost** [comment]
Ah, now I understand. Are you sure that for e.g. Valhalla, or for that matter, any data user, the fully expanded format would be harder to read? Because, each data user must parse and understand the tags as they are in OSM anyway already.

**Comment by ianthetechie** [comment]
I'm fairly certain that Valhalla will *not* be parsing these directly as OSM tags, and they will need some sort of "simplification" of the existing pieces of text anyways for road types such as `UK built-up area`, and vehicle types such as `truck_bus`. The first is completely free-form text that will require application smarts (probably), and the second is one example of a vehicle type for which I could not find an OSM wiki entry.

**Comment by westnordost** [comment]
> for road types such as UK built-up area

Did you see the second table on that wiki page? "UK built-up area" translates to "lit=yes"

**Comment by westnordost** [comment]
Additionally, regarding truck_bus:

The table on the wiki is written in a way that if a data consumer is not interested in or does not understand a certain vehicle-sub-type, it is safe to ignore it. The rules given in `bus` apply to any kind of bus and are overwritten if anything else is defined for e.g. `truck_bus`

**Comment by ianthetechie** [comment]
I guess I picked a bad example ;) I did nod see the table, so thanks for pointing that out! In any event, there are some which simply cannot be translated, such as `urban`, so I'm curious what you propose to do about these.

Maybe you could give a short example of how you want the structure to look, using a complete country as an example?

**Comment by westnordost** [comment]
> some which simply cannot be translated, such as urban, so I'm curious what you propose to do about these.

Well, there is currently no tag for that in OSM. It would be nice if there would be something like `urban=yes/no` or similar in the future. In the meantime, data consumers could use other tell-tale tags. (e.g. `source:maxspeed=XX:urban` etc, but this is a fuzzy mapping). Speaking of which - maybe a third table could be introduced on that wiki page that maps exactly these fuzzy stuff. Fuzzy or not, this would be interesting still for routers.

> Maybe you could give a short example of how you want the structure to look, using a complete country as an example?

There are two options. Let's take this example:

```json
{
  "AA": { "interstate": "60" }
}
```
\+
```json
{
  "interstate": "highway=motorway AND ref~^I"
}
```

Either merge this translation of road types into one big JSON:
```json
{
  "AA": { "highway=motorway AND ref~^I": "60" }
}
```

Or keep the tables separate and make it a duty of the library that dishes out the data to combine it.

I think keeping them separate is fine and more clear, because there needs to be a library anyway, to read and apply the above mentioned "tag filter syntax", and to interpret in which order the rules should be applied, see https://wiki.openstreetmap.org/wiki/Default_speed_limits#How_to_read_this_table .

**Addition:** In the end, a user of the data would want an interface where he can just supply the vehicle type and its properties plus the OSM tags of the road and gets a max speed in return. To have the data in a proper format is only the first step of making it available, the second is that in the end, for data consumers, it is just one line of code to use it.

**Comment by ianthetechie** [comment]
Gotcha. I have tried adding the tag filters to the existing hierarchy. However, there are almost 80 "exceptional" cases right now which cannot be cleanly mapped. See `unmapped_road_types` in parse_utils.py in the updated PR.
