### ISSUE TITLE
Bug: commas in conditional speed restrictions not mapped correctly

### ISSUE THREAD

**Issue by westnordost** [stadiamaps/osm-default-speeds#4]
A speed restriction given in the wiki page like `80 (3.5t, trailer)` is incorrectly mapped to 
```json
[
  "80 (3.5t,",
  "trailer)",
]
```
but it should be 
```json
[
  "80 (3.5t, trailer)",
]
```

See for example Netherlands > motorway.

**Comment by ianthetechie** [comment]
Good catch.
